### PR TITLE
Search components by kwargs

### PR DESCRIPTION
**Pull request by wpjunior**
This PR allows to search components by kwargs (name, group_id, etc).

### CODE REVIEW

**Comment by wpjunior** [comment]
In this case per_page and sorting params will works too

**Comment by dmsimard** [comment]
Oh, the data=kwargs is already there on the other calls, just not this one. All right, looks like I forgot that one.

Thanks for your contribution !

**Comment by wpjunior** [comment]
Could you release a new version for us ?

**Comment by dmsimard** [comment]
@wpjunior sure!
0.2.2 tagged and uploaded to PyPi.

**Comment by wpjunior** [comment]
Thanks @dmsimard =)

**Pull request merged**
